name: Build Python

on:
  push:
    branches:
      - main
    paths:
      - "python/**"
      - ".github/workflows/build-python-images.yml"
  pull_request:
    branches:
      - main
    paths:
      - "python/**"
      - ".github/workflows/build-python-images.yml"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936 # date: 2022-11-21

      - name: Login to Github Packages
        run: docker login ghcr.io -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build 3.10 image
        run: >-
          docker build 
          --build-arg VARIANT=3.10-bullseye
          --tag ghcr.io/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}/python:3.10
          -f python/Dockerfile .
      
      - name: Build 3.11 image
        run: >-
          docker build 
          --build-arg VARIANT=3.11-bullseye
          --tag ghcr.io/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}/python:3.11
          -f python/Dockerfile .

      - name: Push the Docker image
        run: |-
          docker push ghcr.io/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}/python:3.10
          docker push ghcr.io/${GITHUB_REPOSITORY}/${{ github.event.repository.name }}/python:3.11
